# Generated by Django 2.1.1 on 2018-10-02 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('url_name', models.URLField(default='https://www.google.com/', verbose_name='Link')),
                ('category', models.CharField(choices=[('EC', 'Economia'), ('ED', 'Educação'), ('S', 'Saúde'), ('V', 'Violência'), ('D', 'Desemprego'), ('C', 'Corrupção')], default='', max_length=30, verbose_name='Categoria')),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.Candidate')),
            ],
        ),
    ]
