# Generated by Django 2.1.1 on 2018-10-02 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('nickname', models.CharField(max_length=25, verbose_name='Apelido')),
                ('url_name', models.CharField(default='candidato', max_length=25, verbose_name='Nome na URL')),
                ('vice', models.CharField(default='vice', max_length=25, verbose_name='Nome do Vice')),
                ('political_party', models.CharField(max_length=30, verbose_name='Partido')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('color', models.CharField(default='orange', max_length=25, verbose_name='Cor do Partido')),
                ('font_color', models.CharField(default='orange', max_length=25, verbose_name='Cor da fonte')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografia')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.URLField(default='https://twitter.com/', verbose_name='Twitter')),
                ('profile', models.URLField(default='http://lattes.cnpq.br/', verbose_name='Perfil')),
                ('facebook', models.URLField(default='https://www.facebook.com/', verbose_name='Facebook')),
                ('president', models.URLField(default='https://www.google.com/', verbose_name='Presidente')),
                ('vice', models.URLField(default='https://www.google.com/', verbose_name='vice')),
                ('project', models.URLField(default='https://www.google.com/', verbose_name='Projeto')),
                ('nickname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidato.Candidate')),
            ],
        ),
    ]
