# Generated by Django 2.1.1 on 2018-10-02 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(max_length=100, verbose_name='Formação')),
                ('university', models.CharField(max_length=100, verbose_name='Universidade')),
                ('start_date', models.CharField(blank=True, default='_', max_length=30, null=True, verbose_name='Entrada na Universidade')),
                ('end_date', models.CharField(blank=True, default='_', max_length=30, null=True, verbose_name='Saída da Universidade')),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.Candidate')),
            ],
        ),
    ]
