# Generated by Django 2.1.1 on 2018-10-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='sex',
            field=models.CharField(choices=[('NF', 'Não Fornecer'), ('F', 'Feminino'), ('M', 'Masculino')], default='NF', max_length=30, verbose_name='Sexo'),
        ),
    ]
