# Generated by Django 2.1.1 on 2018-10-02 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('url_name', models.URLField(default='https://www.google.com/', verbose_name='Link')),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.Candidate')),
            ],
        ),
    ]
