# Generated by Django 2.1.1 on 2018-10-02 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=150, verbose_name='Cargo')),
                ('employer', models.CharField(max_length=100, verbose_name='Empregador')),
                ('start_date', models.CharField(blank=True, default='_', max_length=10, null=True, verbose_name='Entrada no Cargo')),
                ('end_date', models.CharField(blank=True, default='_', max_length=10, null=True, verbose_name='Saída do Cargo')),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.Candidate')),
            ],
        ),
    ]
